/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustAndSafetyRouteImport } from './routes/trust-and-safety'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MentorFaqsRouteImport } from './routes/mentor-faqs'
import { Route as MentorAgreementRouteImport } from './routes/mentor-agreement'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnerFaqsRouteImport } from './routes/learner-faqs'
import { Route as JourneyWelcomeRouteImport } from './routes/journey-welcome'
import { Route as HowItWorksTrippersRouteImport } from './routes/how-it-works-trippers'
import { Route as HowItWorksHostsRouteImport } from './routes/how-it-works-hosts'
import { Route as GiftRouteImport } from './routes/gift'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FirstLessonGuideRouteImport } from './routes/first-lesson-guide'
import { Route as DataHandlingRouteImport } from './routes/data-handling'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as BecomeAnAideRouteImport } from './routes/become-an-aide'
import { Route as BecomeAMentorRouteImport } from './routes/become-a-mentor'
import { Route as AcceptableUsePolicyRouteImport } from './routes/acceptable-use-policy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as PPathSlugRouteImport } from './routes/p.$pathSlug'
import { Route as OnboardingLearnerRouteImport } from './routes/onboarding.learner'
import { Route as OnboardingChoiceRouteImport } from './routes/onboarding.choice'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as MentorCreatePathRouteImport } from './routes/mentor.create-path'
import { Route as MMentorSlugRouteImport } from './routes/m.$mentorSlug'
import { Route as GiftSuccessRouteImport } from './routes/gift.success'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMyLearningRouteImport } from './routes/_authenticated/my-learning'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookingReviewRouteImport } from './routes/_authenticated/booking-review'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as OnboardingLearnerResultsRouteImport } from './routes/onboarding.learner.results'
import { Route as OnboardingLearnerPaceRouteImport } from './routes/onboarding.learner.pace'
import { Route as OnboardingLearnerDeviceRouteImport } from './routes/onboarding.learner.device'
import { Route as CCategorySlugListingSlugRouteImport } from './routes/c.$categorySlug.$listingSlug'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsPayoutsRouteImport } from './routes/_authenticated/settings.payouts'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings.billing'
import { Route as AuthenticatedOperatorPreviewRouteImport } from './routes/_authenticated/operator.preview'
import { Route as AuthenticatedDashboardUpcomingSessionsRouteImport } from './routes/_authenticated/dashboard.upcoming-sessions'
import { Route as AuthenticatedDashboardMyOrdersRouteImport } from './routes/_authenticated/dashboard.my-orders'
import { Route as AuthenticatedDashboardMyListingRouteImport } from './routes/_authenticated/dashboard.my-listing'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardLearnerRouteImport } from './routes/_authenticated/dashboard.learner'
import { Route as AuthenticatedDashboardFavoritesRouteImport } from './routes/_authenticated/dashboard.favorites'
import { Route as AuthenticatedDashboardEarningsBookingsRouteImport } from './routes/_authenticated/dashboard.earnings-bookings'
import { Route as AuthenticatedDashboardEarningsRouteImport } from './routes/_authenticated/dashboard.earnings'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard.bookings'
import { Route as AuthenticatedDashboardAideRouteImport } from './routes/_authenticated/dashboard.aide'
import { Route as AuthenticatedClassroomOrderIdRouteImport } from './routes/_authenticated/classroom.$orderId'
import { Route as AuthenticatedCertificateOrderIdRouteImport } from './routes/_authenticated/certificate.$orderId'
import { Route as AdminAdminTransactionsRouteImport } from './routes/_admin/admin.transactions'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminSearchSeoRouteImport } from './routes/_admin/admin.search-seo'
import { Route as AdminAdminReviewsRouteImport } from './routes/_admin/admin.reviews'
import { Route as AdminAdminQueueRouteImport } from './routes/_admin/admin.queue'
import { Route as AdminAdminListingsRouteImport } from './routes/_admin/admin.listings'
import { Route as AuthenticatedDashboardMessagesIndexRouteImport } from './routes/_authenticated/dashboard.messages.index'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin.users.index'
import { Route as AdminAdminSearchSeoIndexRouteImport } from './routes/_admin/admin.search-seo.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicHooksCleanupOldMessagesRouteImport } from './routes/api/public/hooks/cleanup-old-messages'
import { Route as AuthenticatedDashboardMessagesThreadIdRouteImport } from './routes/_authenticated/dashboard.messages.$threadId'
import { Route as AuthenticatedDashboardLearnerUpcomingSessionsRouteImport } from './routes/_authenticated/dashboard.learner.upcoming-sessions'
import { Route as AuthenticatedDashboardLearnerScheduleRouteImport } from './routes/_authenticated/dashboard.learner.schedule'
import { Route as AuthenticatedDashboardLearnerPurchasesRouteImport } from './routes/_authenticated/dashboard.learner.purchases'
import { Route as AuthenticatedDashboardAideCoursesRouteImport } from './routes/_authenticated/dashboard.aide.courses'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/_admin/admin.users.$userId'
import { Route as AdminAdminSettingsStripeRouteImport } from './routes/_admin/admin.settings.stripe'
import { Route as AdminAdminSettingsPaymentsRouteImport } from './routes/_admin/admin.settings.payments'
import { Route as AdminAdminSettingsNewsletterRouteImport } from './routes/_admin/admin.settings.newsletter'
import { Route as AdminAdminSettingsHeroRouteImport } from './routes/_admin/admin.settings.hero'
import { Route as AdminAdminSettingsEmailTemplatesRouteImport } from './routes/_admin/admin.settings.email-templates'
import { Route as AdminAdminSettingsCategoriesRouteImport } from './routes/_admin/admin.settings.categories'
import { Route as AdminAdminSearchSeoTagsRouteImport } from './routes/_admin/admin.search-seo.tags'
import { Route as AdminAdminSettingsPagesIndexRouteImport } from './routes/_admin/admin.settings.pages.index'
import { Route as AuthenticatedDashboardListingsJourneyIdShowcaseRouteImport } from './routes/_authenticated/dashboard.listings.$journeyId.showcase'
import { Route as AuthenticatedDashboardListingsJourneyIdCouponsRouteImport } from './routes/_authenticated/dashboard.listings.$journeyId.coupons'
import { Route as AdminAdminSettingsPagesPageIdRouteImport } from './routes/_admin/admin.settings.pages.$pageId'

const TrustAndSafetyRoute = TrustAndSafetyRouteImport.update({
  id: '/trust-and-safety',
  path: '/trust-and-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorFaqsRoute = MentorFaqsRouteImport.update({
  id: '/mentor-faqs',
  path: '/mentor-faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAgreementRoute = MentorAgreementRouteImport.update({
  id: '/mentor-agreement',
  path: '/mentor-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerFaqsRoute = LearnerFaqsRouteImport.update({
  id: '/learner-faqs',
  path: '/learner-faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyWelcomeRoute = JourneyWelcomeRouteImport.update({
  id: '/journey-welcome',
  path: '/journey-welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksTrippersRoute = HowItWorksTrippersRouteImport.update({
  id: '/how-it-works-trippers',
  path: '/how-it-works-trippers',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksHostsRoute = HowItWorksHostsRouteImport.update({
  id: '/how-it-works-hosts',
  path: '/how-it-works-hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftRoute = GiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstLessonGuideRoute = FirstLessonGuideRouteImport.update({
  id: '/first-lesson-guide',
  path: '/first-lesson-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DataHandlingRoute = DataHandlingRouteImport.update({
  id: '/data-handling',
  path: '/data-handling',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAnAideRoute = BecomeAnAideRouteImport.update({
  id: '/become-an-aide',
  path: '/become-an-aide',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAMentorRoute = BecomeAMentorRouteImport.update({
  id: '/become-a-mentor',
  path: '/become-a-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUsePolicyRoute = AcceptableUsePolicyRouteImport.update({
  id: '/acceptable-use-policy',
  path: '/acceptable-use-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PPathSlugRoute = PPathSlugRouteImport.update({
  id: '/p/$pathSlug',
  path: '/p/$pathSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLearnerRoute = OnboardingLearnerRouteImport.update({
  id: '/onboarding/learner',
  path: '/onboarding/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingChoiceRoute = OnboardingChoiceRouteImport.update({
  id: '/onboarding/choice',
  path: '/onboarding/choice',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/messages/$threadId',
  path: '/messages/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorCreatePathRoute = MentorCreatePathRouteImport.update({
  id: '/mentor/create-path',
  path: '/mentor/create-path',
  getParentRoute: () => rootRouteImport,
} as any)
const MMentorSlugRoute = MMentorSlugRouteImport.update({
  id: '/m/$mentorSlug',
  path: '/m/$mentorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftSuccessRoute = GiftSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => GiftRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyLearningRoute = AuthenticatedMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingReviewRoute =
  AuthenticatedBookingReviewRouteImport.update({
    id: '/booking-review',
    path: '/booking-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const OnboardingLearnerResultsRoute =
  OnboardingLearnerResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => OnboardingLearnerRoute,
  } as any)
const OnboardingLearnerPaceRoute = OnboardingLearnerPaceRouteImport.update({
  id: '/pace',
  path: '/pace',
  getParentRoute: () => OnboardingLearnerRoute,
} as any)
const OnboardingLearnerDeviceRoute = OnboardingLearnerDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => OnboardingLearnerRoute,
} as any)
const CCategorySlugListingSlugRoute =
  CCategorySlugListingSlugRouteImport.update({
    id: '/c/$categorySlug/$listingSlug',
    path: '/c/$categorySlug/$listingSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPayoutsRoute =
  AuthenticatedSettingsPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedOperatorPreviewRoute =
  AuthenticatedOperatorPreviewRouteImport.update({
    id: '/operator/preview',
    path: '/operator/preview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardUpcomingSessionsRoute =
  AuthenticatedDashboardUpcomingSessionsRouteImport.update({
    id: '/upcoming-sessions',
    path: '/upcoming-sessions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyOrdersRoute =
  AuthenticatedDashboardMyOrdersRouteImport.update({
    id: '/my-orders',
    path: '/my-orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyListingRoute =
  AuthenticatedDashboardMyListingRouteImport.update({
    id: '/my-listing',
    path: '/my-listing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLearnerRoute =
  AuthenticatedDashboardLearnerRouteImport.update({
    id: '/learner',
    path: '/learner',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFavoritesRoute =
  AuthenticatedDashboardFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEarningsBookingsRoute =
  AuthenticatedDashboardEarningsBookingsRouteImport.update({
    id: '/earnings-bookings',
    path: '/earnings-bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEarningsRoute =
  AuthenticatedDashboardEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAideRoute =
  AuthenticatedDashboardAideRouteImport.update({
    id: '/aide',
    path: '/aide',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedClassroomOrderIdRoute =
  AuthenticatedClassroomOrderIdRouteImport.update({
    id: '/classroom/$orderId',
    path: '/classroom/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCertificateOrderIdRoute =
  AuthenticatedCertificateOrderIdRouteImport.update({
    id: '/certificate/$orderId',
    path: '/certificate/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminTransactionsRoute = AdminAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSearchSeoRoute = AdminAdminSearchSeoRouteImport.update({
  id: '/search-seo',
  path: '/search-seo',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminReviewsRoute = AdminAdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminQueueRoute = AdminAdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminListingsRoute = AdminAdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedDashboardMessagesIndexRoute =
  AuthenticatedDashboardMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardMessagesRoute,
  } as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSearchSeoIndexRoute =
  AdminAdminSearchSeoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminSearchSeoRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupOldMessagesRoute =
  ApiPublicHooksCleanupOldMessagesRouteImport.update({
    id: '/api/public/hooks/cleanup-old-messages',
    path: '/api/public/hooks/cleanup-old-messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardMessagesThreadIdRoute =
  AuthenticatedDashboardMessagesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedDashboardMessagesRoute,
  } as any)
const AuthenticatedDashboardLearnerUpcomingSessionsRoute =
  AuthenticatedDashboardLearnerUpcomingSessionsRouteImport.update({
    id: '/upcoming-sessions',
    path: '/upcoming-sessions',
    getParentRoute: () => AuthenticatedDashboardLearnerRoute,
  } as any)
const AuthenticatedDashboardLearnerScheduleRoute =
  AuthenticatedDashboardLearnerScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedDashboardLearnerRoute,
  } as any)
const AuthenticatedDashboardLearnerPurchasesRoute =
  AuthenticatedDashboardLearnerPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedDashboardLearnerRoute,
  } as any)
const AuthenticatedDashboardAideCoursesRoute =
  AuthenticatedDashboardAideCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedDashboardAideRoute,
  } as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsStripeRoute =
  AdminAdminSettingsStripeRouteImport.update({
    id: '/stripe',
    path: '/stripe',
    getParentRoute: () => AdminAdminSettingsRoute,
  } as any)
const AdminAdminSettingsPaymentsRoute =
  AdminAdminSettingsPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AdminAdminSettingsRoute,
  } as any)
const AdminAdminSettingsNewsletterRoute =
  AdminAdminSettingsNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AdminAdminSettingsRoute,
  } as any)
const AdminAdminSettingsHeroRoute = AdminAdminSettingsHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminAdminSettingsRoute,
} as any)
const AdminAdminSettingsEmailTemplatesRoute =
  AdminAdminSettingsEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AdminAdminSettingsRoute,
  } as any)
const AdminAdminSettingsCategoriesRoute =
  AdminAdminSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminAdminSettingsRoute,
  } as any)
const AdminAdminSearchSeoTagsRoute = AdminAdminSearchSeoTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminAdminSearchSeoRoute,
} as any)
const AdminAdminSettingsPagesIndexRoute =
  AdminAdminSettingsPagesIndexRouteImport.update({
    id: '/pages/',
    path: '/pages/',
    getParentRoute: () => AdminAdminSettingsRoute,
  } as any)
const AuthenticatedDashboardListingsJourneyIdShowcaseRoute =
  AuthenticatedDashboardListingsJourneyIdShowcaseRouteImport.update({
    id: '/listings/$journeyId/showcase',
    path: '/listings/$journeyId/showcase',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardListingsJourneyIdCouponsRoute =
  AuthenticatedDashboardListingsJourneyIdCouponsRouteImport.update({
    id: '/listings/$journeyId/coupons',
    path: '/listings/$journeyId/coupons',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminSettingsPagesPageIdRoute =
  AdminAdminSettingsPagesPageIdRouteImport.update({
    id: '/pages/$pageId',
    path: '/pages/$pageId',
    getParentRoute: () => AdminAdminSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use-policy': typeof AcceptableUsePolicyRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/become-an-aide': typeof BecomeAnAideRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/data-handling': typeof DataHandlingRoute
  '/first-lesson-guide': typeof FirstLessonGuideRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gift': typeof GiftRouteWithChildren
  '/how-it-works-hosts': typeof HowItWorksHostsRoute
  '/how-it-works-trippers': typeof HowItWorksTrippersRoute
  '/journey-welcome': typeof JourneyWelcomeRoute
  '/learner-faqs': typeof LearnerFaqsRoute
  '/login': typeof LoginRoute
  '/mentor-agreement': typeof MentorAgreementRoute
  '/mentor-faqs': typeof MentorFaqsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-and-safety': typeof TrustAndSafetyRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/booking-review': typeof AuthenticatedBookingReviewRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/gift/success': typeof GiftSuccessRoute
  '/m/$mentorSlug': typeof MMentorSlugRoute
  '/mentor/create-path': typeof MentorCreatePathRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/onboarding/choice': typeof OnboardingChoiceRoute
  '/onboarding/learner': typeof OnboardingLearnerRouteWithChildren
  '/p/$pathSlug': typeof PPathSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/listings': typeof AdminAdminListingsRoute
  '/admin/queue': typeof AdminAdminQueueRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/search-seo': typeof AdminAdminSearchSeoRouteWithChildren
  '/admin/settings': typeof AdminAdminSettingsRouteWithChildren
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/certificate/$orderId': typeof AuthenticatedCertificateOrderIdRoute
  '/classroom/$orderId': typeof AuthenticatedClassroomOrderIdRoute
  '/dashboard/aide': typeof AuthenticatedDashboardAideRouteWithChildren
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/earnings': typeof AuthenticatedDashboardEarningsRoute
  '/dashboard/earnings-bookings': typeof AuthenticatedDashboardEarningsBookingsRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/learner': typeof AuthenticatedDashboardLearnerRouteWithChildren
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRouteWithChildren
  '/dashboard/my-listing': typeof AuthenticatedDashboardMyListingRoute
  '/dashboard/my-orders': typeof AuthenticatedDashboardMyOrdersRoute
  '/dashboard/upcoming-sessions': typeof AuthenticatedDashboardUpcomingSessionsRoute
  '/operator/preview': typeof AuthenticatedOperatorPreviewRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/payouts': typeof AuthenticatedSettingsPayoutsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/c/$categorySlug/$listingSlug': typeof CCategorySlugListingSlugRoute
  '/onboarding/learner/device': typeof OnboardingLearnerDeviceRoute
  '/onboarding/learner/pace': typeof OnboardingLearnerPaceRoute
  '/onboarding/learner/results': typeof OnboardingLearnerResultsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/search-seo/tags': typeof AdminAdminSearchSeoTagsRoute
  '/admin/settings/categories': typeof AdminAdminSettingsCategoriesRoute
  '/admin/settings/email-templates': typeof AdminAdminSettingsEmailTemplatesRoute
  '/admin/settings/hero': typeof AdminAdminSettingsHeroRoute
  '/admin/settings/newsletter': typeof AdminAdminSettingsNewsletterRoute
  '/admin/settings/payments': typeof AdminAdminSettingsPaymentsRoute
  '/admin/settings/stripe': typeof AdminAdminSettingsStripeRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/dashboard/aide/courses': typeof AuthenticatedDashboardAideCoursesRoute
  '/dashboard/learner/purchases': typeof AuthenticatedDashboardLearnerPurchasesRoute
  '/dashboard/learner/schedule': typeof AuthenticatedDashboardLearnerScheduleRoute
  '/dashboard/learner/upcoming-sessions': typeof AuthenticatedDashboardLearnerUpcomingSessionsRoute
  '/dashboard/messages/$threadId': typeof AuthenticatedDashboardMessagesThreadIdRoute
  '/api/public/hooks/cleanup-old-messages': typeof ApiPublicHooksCleanupOldMessagesRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/search-seo/': typeof AdminAdminSearchSeoIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
  '/dashboard/messages/': typeof AuthenticatedDashboardMessagesIndexRoute
  '/admin/settings/pages/$pageId': typeof AdminAdminSettingsPagesPageIdRoute
  '/dashboard/listings/$journeyId/coupons': typeof AuthenticatedDashboardListingsJourneyIdCouponsRoute
  '/dashboard/listings/$journeyId/showcase': typeof AuthenticatedDashboardListingsJourneyIdShowcaseRoute
  '/admin/settings/pages/': typeof AdminAdminSettingsPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use-policy': typeof AcceptableUsePolicyRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/become-an-aide': typeof BecomeAnAideRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/data-handling': typeof DataHandlingRoute
  '/first-lesson-guide': typeof FirstLessonGuideRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gift': typeof GiftRouteWithChildren
  '/how-it-works-hosts': typeof HowItWorksHostsRoute
  '/how-it-works-trippers': typeof HowItWorksTrippersRoute
  '/journey-welcome': typeof JourneyWelcomeRoute
  '/learner-faqs': typeof LearnerFaqsRoute
  '/login': typeof LoginRoute
  '/mentor-agreement': typeof MentorAgreementRoute
  '/mentor-faqs': typeof MentorFaqsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-and-safety': typeof TrustAndSafetyRoute
  '/booking-review': typeof AuthenticatedBookingReviewRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/gift/success': typeof GiftSuccessRoute
  '/m/$mentorSlug': typeof MMentorSlugRoute
  '/mentor/create-path': typeof MentorCreatePathRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/onboarding/choice': typeof OnboardingChoiceRoute
  '/onboarding/learner': typeof OnboardingLearnerRouteWithChildren
  '/p/$pathSlug': typeof PPathSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/listings': typeof AdminAdminListingsRoute
  '/admin/queue': typeof AdminAdminQueueRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/settings': typeof AdminAdminSettingsRouteWithChildren
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/certificate/$orderId': typeof AuthenticatedCertificateOrderIdRoute
  '/classroom/$orderId': typeof AuthenticatedClassroomOrderIdRoute
  '/dashboard/aide': typeof AuthenticatedDashboardAideRouteWithChildren
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/earnings': typeof AuthenticatedDashboardEarningsRoute
  '/dashboard/earnings-bookings': typeof AuthenticatedDashboardEarningsBookingsRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/learner': typeof AuthenticatedDashboardLearnerRouteWithChildren
  '/dashboard/my-listing': typeof AuthenticatedDashboardMyListingRoute
  '/dashboard/my-orders': typeof AuthenticatedDashboardMyOrdersRoute
  '/dashboard/upcoming-sessions': typeof AuthenticatedDashboardUpcomingSessionsRoute
  '/operator/preview': typeof AuthenticatedOperatorPreviewRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/payouts': typeof AuthenticatedSettingsPayoutsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/c/$categorySlug/$listingSlug': typeof CCategorySlugListingSlugRoute
  '/onboarding/learner/device': typeof OnboardingLearnerDeviceRoute
  '/onboarding/learner/pace': typeof OnboardingLearnerPaceRoute
  '/onboarding/learner/results': typeof OnboardingLearnerResultsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/search-seo/tags': typeof AdminAdminSearchSeoTagsRoute
  '/admin/settings/categories': typeof AdminAdminSettingsCategoriesRoute
  '/admin/settings/email-templates': typeof AdminAdminSettingsEmailTemplatesRoute
  '/admin/settings/hero': typeof AdminAdminSettingsHeroRoute
  '/admin/settings/newsletter': typeof AdminAdminSettingsNewsletterRoute
  '/admin/settings/payments': typeof AdminAdminSettingsPaymentsRoute
  '/admin/settings/stripe': typeof AdminAdminSettingsStripeRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/dashboard/aide/courses': typeof AuthenticatedDashboardAideCoursesRoute
  '/dashboard/learner/purchases': typeof AuthenticatedDashboardLearnerPurchasesRoute
  '/dashboard/learner/schedule': typeof AuthenticatedDashboardLearnerScheduleRoute
  '/dashboard/learner/upcoming-sessions': typeof AuthenticatedDashboardLearnerUpcomingSessionsRoute
  '/dashboard/messages/$threadId': typeof AuthenticatedDashboardMessagesThreadIdRoute
  '/api/public/hooks/cleanup-old-messages': typeof ApiPublicHooksCleanupOldMessagesRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/search-seo': typeof AdminAdminSearchSeoIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesIndexRoute
  '/admin/settings/pages/$pageId': typeof AdminAdminSettingsPagesPageIdRoute
  '/dashboard/listings/$journeyId/coupons': typeof AuthenticatedDashboardListingsJourneyIdCouponsRoute
  '/dashboard/listings/$journeyId/showcase': typeof AuthenticatedDashboardListingsJourneyIdShowcaseRoute
  '/admin/settings/pages': typeof AdminAdminSettingsPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/acceptable-use-policy': typeof AcceptableUsePolicyRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/become-an-aide': typeof BecomeAnAideRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/data-handling': typeof DataHandlingRoute
  '/first-lesson-guide': typeof FirstLessonGuideRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gift': typeof GiftRouteWithChildren
  '/how-it-works-hosts': typeof HowItWorksHostsRoute
  '/how-it-works-trippers': typeof HowItWorksTrippersRoute
  '/journey-welcome': typeof JourneyWelcomeRoute
  '/learner-faqs': typeof LearnerFaqsRoute
  '/login': typeof LoginRoute
  '/mentor-agreement': typeof MentorAgreementRoute
  '/mentor-faqs': typeof MentorFaqsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-and-safety': typeof TrustAndSafetyRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/booking-review': typeof AuthenticatedBookingReviewRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/my-learning': typeof AuthenticatedMyLearningRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/gift/success': typeof GiftSuccessRoute
  '/m/$mentorSlug': typeof MMentorSlugRoute
  '/mentor/create-path': typeof MentorCreatePathRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/onboarding/choice': typeof OnboardingChoiceRoute
  '/onboarding/learner': typeof OnboardingLearnerRouteWithChildren
  '/p/$pathSlug': typeof PPathSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/_admin/admin/listings': typeof AdminAdminListingsRoute
  '/_admin/admin/queue': typeof AdminAdminQueueRoute
  '/_admin/admin/reviews': typeof AdminAdminReviewsRoute
  '/_admin/admin/search-seo': typeof AdminAdminSearchSeoRouteWithChildren
  '/_admin/admin/settings': typeof AdminAdminSettingsRouteWithChildren
  '/_admin/admin/transactions': typeof AdminAdminTransactionsRoute
  '/_authenticated/certificate/$orderId': typeof AuthenticatedCertificateOrderIdRoute
  '/_authenticated/classroom/$orderId': typeof AuthenticatedClassroomOrderIdRoute
  '/_authenticated/dashboard/aide': typeof AuthenticatedDashboardAideRouteWithChildren
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/earnings': typeof AuthenticatedDashboardEarningsRoute
  '/_authenticated/dashboard/earnings-bookings': typeof AuthenticatedDashboardEarningsBookingsRoute
  '/_authenticated/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/_authenticated/dashboard/learner': typeof AuthenticatedDashboardLearnerRouteWithChildren
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRouteWithChildren
  '/_authenticated/dashboard/my-listing': typeof AuthenticatedDashboardMyListingRoute
  '/_authenticated/dashboard/my-orders': typeof AuthenticatedDashboardMyOrdersRoute
  '/_authenticated/dashboard/upcoming-sessions': typeof AuthenticatedDashboardUpcomingSessionsRoute
  '/_authenticated/operator/preview': typeof AuthenticatedOperatorPreviewRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/payouts': typeof AuthenticatedSettingsPayoutsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/c/$categorySlug/$listingSlug': typeof CCategorySlugListingSlugRoute
  '/onboarding/learner/device': typeof OnboardingLearnerDeviceRoute
  '/onboarding/learner/pace': typeof OnboardingLearnerPaceRoute
  '/onboarding/learner/results': typeof OnboardingLearnerResultsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/search-seo/tags': typeof AdminAdminSearchSeoTagsRoute
  '/_admin/admin/settings/categories': typeof AdminAdminSettingsCategoriesRoute
  '/_admin/admin/settings/email-templates': typeof AdminAdminSettingsEmailTemplatesRoute
  '/_admin/admin/settings/hero': typeof AdminAdminSettingsHeroRoute
  '/_admin/admin/settings/newsletter': typeof AdminAdminSettingsNewsletterRoute
  '/_admin/admin/settings/payments': typeof AdminAdminSettingsPaymentsRoute
  '/_admin/admin/settings/stripe': typeof AdminAdminSettingsStripeRoute
  '/_admin/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/_authenticated/dashboard/aide/courses': typeof AuthenticatedDashboardAideCoursesRoute
  '/_authenticated/dashboard/learner/purchases': typeof AuthenticatedDashboardLearnerPurchasesRoute
  '/_authenticated/dashboard/learner/schedule': typeof AuthenticatedDashboardLearnerScheduleRoute
  '/_authenticated/dashboard/learner/upcoming-sessions': typeof AuthenticatedDashboardLearnerUpcomingSessionsRoute
  '/_authenticated/dashboard/messages/$threadId': typeof AuthenticatedDashboardMessagesThreadIdRoute
  '/api/public/hooks/cleanup-old-messages': typeof ApiPublicHooksCleanupOldMessagesRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/_admin/admin/search-seo/': typeof AdminAdminSearchSeoIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
  '/_authenticated/dashboard/messages/': typeof AuthenticatedDashboardMessagesIndexRoute
  '/_admin/admin/settings/pages/$pageId': typeof AdminAdminSettingsPagesPageIdRoute
  '/_authenticated/dashboard/listings/$journeyId/coupons': typeof AuthenticatedDashboardListingsJourneyIdCouponsRoute
  '/_authenticated/dashboard/listings/$journeyId/showcase': typeof AuthenticatedDashboardListingsJourneyIdShowcaseRoute
  '/_admin/admin/settings/pages/': typeof AdminAdminSettingsPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acceptable-use-policy'
    | '/become-a-mentor'
    | '/become-an-aide'
    | '/cancellation-policy'
    | '/checkout'
    | '/contact'
    | '/data-handling'
    | '/first-lesson-guide'
    | '/forgot-password'
    | '/gift'
    | '/how-it-works-hosts'
    | '/how-it-works-trippers'
    | '/journey-welcome'
    | '/learner-faqs'
    | '/login'
    | '/mentor-agreement'
    | '/mentor-faqs'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-and-safety'
    | '/admin'
    | '/booking-review'
    | '/dashboard'
    | '/my-learning'
    | '/settings'
    | '/checkout/success'
    | '/gift/success'
    | '/m/$mentorSlug'
    | '/mentor/create-path'
    | '/messages/$threadId'
    | '/onboarding/choice'
    | '/onboarding/learner'
    | '/p/$pathSlug'
    | '/pages/$slug'
    | '/admin/listings'
    | '/admin/queue'
    | '/admin/reviews'
    | '/admin/search-seo'
    | '/admin/settings'
    | '/admin/transactions'
    | '/certificate/$orderId'
    | '/classroom/$orderId'
    | '/dashboard/aide'
    | '/dashboard/bookings'
    | '/dashboard/earnings'
    | '/dashboard/earnings-bookings'
    | '/dashboard/favorites'
    | '/dashboard/learner'
    | '/dashboard/messages'
    | '/dashboard/my-listing'
    | '/dashboard/my-orders'
    | '/dashboard/upcoming-sessions'
    | '/operator/preview'
    | '/settings/billing'
    | '/settings/payouts'
    | '/settings/profile'
    | '/settings/security'
    | '/c/$categorySlug/$listingSlug'
    | '/onboarding/learner/device'
    | '/onboarding/learner/pace'
    | '/onboarding/learner/results'
    | '/admin/'
    | '/admin/search-seo/tags'
    | '/admin/settings/categories'
    | '/admin/settings/email-templates'
    | '/admin/settings/hero'
    | '/admin/settings/newsletter'
    | '/admin/settings/payments'
    | '/admin/settings/stripe'
    | '/admin/users/$userId'
    | '/dashboard/aide/courses'
    | '/dashboard/learner/purchases'
    | '/dashboard/learner/schedule'
    | '/dashboard/learner/upcoming-sessions'
    | '/dashboard/messages/$threadId'
    | '/api/public/hooks/cleanup-old-messages'
    | '/api/public/stripe/webhook'
    | '/admin/search-seo/'
    | '/admin/users/'
    | '/dashboard/messages/'
    | '/admin/settings/pages/$pageId'
    | '/dashboard/listings/$journeyId/coupons'
    | '/dashboard/listings/$journeyId/showcase'
    | '/admin/settings/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acceptable-use-policy'
    | '/become-a-mentor'
    | '/become-an-aide'
    | '/cancellation-policy'
    | '/checkout'
    | '/contact'
    | '/data-handling'
    | '/first-lesson-guide'
    | '/forgot-password'
    | '/gift'
    | '/how-it-works-hosts'
    | '/how-it-works-trippers'
    | '/journey-welcome'
    | '/learner-faqs'
    | '/login'
    | '/mentor-agreement'
    | '/mentor-faqs'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-and-safety'
    | '/booking-review'
    | '/dashboard'
    | '/my-learning'
    | '/settings'
    | '/checkout/success'
    | '/gift/success'
    | '/m/$mentorSlug'
    | '/mentor/create-path'
    | '/messages/$threadId'
    | '/onboarding/choice'
    | '/onboarding/learner'
    | '/p/$pathSlug'
    | '/pages/$slug'
    | '/admin/listings'
    | '/admin/queue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/transactions'
    | '/certificate/$orderId'
    | '/classroom/$orderId'
    | '/dashboard/aide'
    | '/dashboard/bookings'
    | '/dashboard/earnings'
    | '/dashboard/earnings-bookings'
    | '/dashboard/favorites'
    | '/dashboard/learner'
    | '/dashboard/my-listing'
    | '/dashboard/my-orders'
    | '/dashboard/upcoming-sessions'
    | '/operator/preview'
    | '/settings/billing'
    | '/settings/payouts'
    | '/settings/profile'
    | '/settings/security'
    | '/c/$categorySlug/$listingSlug'
    | '/onboarding/learner/device'
    | '/onboarding/learner/pace'
    | '/onboarding/learner/results'
    | '/admin'
    | '/admin/search-seo/tags'
    | '/admin/settings/categories'
    | '/admin/settings/email-templates'
    | '/admin/settings/hero'
    | '/admin/settings/newsletter'
    | '/admin/settings/payments'
    | '/admin/settings/stripe'
    | '/admin/users/$userId'
    | '/dashboard/aide/courses'
    | '/dashboard/learner/purchases'
    | '/dashboard/learner/schedule'
    | '/dashboard/learner/upcoming-sessions'
    | '/dashboard/messages/$threadId'
    | '/api/public/hooks/cleanup-old-messages'
    | '/api/public/stripe/webhook'
    | '/admin/search-seo'
    | '/admin/users'
    | '/dashboard/messages'
    | '/admin/settings/pages/$pageId'
    | '/dashboard/listings/$journeyId/coupons'
    | '/dashboard/listings/$journeyId/showcase'
    | '/admin/settings/pages'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/about'
    | '/acceptable-use-policy'
    | '/become-a-mentor'
    | '/become-an-aide'
    | '/cancellation-policy'
    | '/checkout'
    | '/contact'
    | '/data-handling'
    | '/first-lesson-guide'
    | '/forgot-password'
    | '/gift'
    | '/how-it-works-hosts'
    | '/how-it-works-trippers'
    | '/journey-welcome'
    | '/learner-faqs'
    | '/login'
    | '/mentor-agreement'
    | '/mentor-faqs'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-and-safety'
    | '/_admin/admin'
    | '/_authenticated/booking-review'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-learning'
    | '/_authenticated/settings'
    | '/checkout/success'
    | '/gift/success'
    | '/m/$mentorSlug'
    | '/mentor/create-path'
    | '/messages/$threadId'
    | '/onboarding/choice'
    | '/onboarding/learner'
    | '/p/$pathSlug'
    | '/pages/$slug'
    | '/_admin/admin/listings'
    | '/_admin/admin/queue'
    | '/_admin/admin/reviews'
    | '/_admin/admin/search-seo'
    | '/_admin/admin/settings'
    | '/_admin/admin/transactions'
    | '/_authenticated/certificate/$orderId'
    | '/_authenticated/classroom/$orderId'
    | '/_authenticated/dashboard/aide'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/earnings'
    | '/_authenticated/dashboard/earnings-bookings'
    | '/_authenticated/dashboard/favorites'
    | '/_authenticated/dashboard/learner'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/my-listing'
    | '/_authenticated/dashboard/my-orders'
    | '/_authenticated/dashboard/upcoming-sessions'
    | '/_authenticated/operator/preview'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/payouts'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/c/$categorySlug/$listingSlug'
    | '/onboarding/learner/device'
    | '/onboarding/learner/pace'
    | '/onboarding/learner/results'
    | '/_admin/admin/'
    | '/_admin/admin/search-seo/tags'
    | '/_admin/admin/settings/categories'
    | '/_admin/admin/settings/email-templates'
    | '/_admin/admin/settings/hero'
    | '/_admin/admin/settings/newsletter'
    | '/_admin/admin/settings/payments'
    | '/_admin/admin/settings/stripe'
    | '/_admin/admin/users/$userId'
    | '/_authenticated/dashboard/aide/courses'
    | '/_authenticated/dashboard/learner/purchases'
    | '/_authenticated/dashboard/learner/schedule'
    | '/_authenticated/dashboard/learner/upcoming-sessions'
    | '/_authenticated/dashboard/messages/$threadId'
    | '/api/public/hooks/cleanup-old-messages'
    | '/api/public/stripe/webhook'
    | '/_admin/admin/search-seo/'
    | '/_admin/admin/users/'
    | '/_authenticated/dashboard/messages/'
    | '/_admin/admin/settings/pages/$pageId'
    | '/_authenticated/dashboard/listings/$journeyId/coupons'
    | '/_authenticated/dashboard/listings/$journeyId/showcase'
    | '/_admin/admin/settings/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptableUsePolicyRoute: typeof AcceptableUsePolicyRoute
  BecomeAMentorRoute: typeof BecomeAMentorRoute
  BecomeAnAideRoute: typeof BecomeAnAideRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DataHandlingRoute: typeof DataHandlingRoute
  FirstLessonGuideRoute: typeof FirstLessonGuideRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GiftRoute: typeof GiftRouteWithChildren
  HowItWorksHostsRoute: typeof HowItWorksHostsRoute
  HowItWorksTrippersRoute: typeof HowItWorksTrippersRoute
  JourneyWelcomeRoute: typeof JourneyWelcomeRoute
  LearnerFaqsRoute: typeof LearnerFaqsRoute
  LoginRoute: typeof LoginRoute
  MentorAgreementRoute: typeof MentorAgreementRoute
  MentorFaqsRoute: typeof MentorFaqsRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustAndSafetyRoute: typeof TrustAndSafetyRoute
  MMentorSlugRoute: typeof MMentorSlugRoute
  MentorCreatePathRoute: typeof MentorCreatePathRoute
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
  OnboardingChoiceRoute: typeof OnboardingChoiceRoute
  OnboardingLearnerRoute: typeof OnboardingLearnerRouteWithChildren
  PPathSlugRoute: typeof PPathSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  CCategorySlugListingSlugRoute: typeof CCategorySlugListingSlugRoute
  ApiPublicHooksCleanupOldMessagesRoute: typeof ApiPublicHooksCleanupOldMessagesRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-and-safety': {
      id: '/trust-and-safety'
      path: '/trust-and-safety'
      fullPath: '/trust-and-safety'
      preLoaderRoute: typeof TrustAndSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-faqs': {
      id: '/mentor-faqs'
      path: '/mentor-faqs'
      fullPath: '/mentor-faqs'
      preLoaderRoute: typeof MentorFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-agreement': {
      id: '/mentor-agreement'
      path: '/mentor-agreement'
      fullPath: '/mentor-agreement'
      preLoaderRoute: typeof MentorAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner-faqs': {
      id: '/learner-faqs'
      path: '/learner-faqs'
      fullPath: '/learner-faqs'
      preLoaderRoute: typeof LearnerFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey-welcome': {
      id: '/journey-welcome'
      path: '/journey-welcome'
      fullPath: '/journey-welcome'
      preLoaderRoute: typeof JourneyWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works-trippers': {
      id: '/how-it-works-trippers'
      path: '/how-it-works-trippers'
      fullPath: '/how-it-works-trippers'
      preLoaderRoute: typeof HowItWorksTrippersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works-hosts': {
      id: '/how-it-works-hosts'
      path: '/how-it-works-hosts'
      fullPath: '/how-it-works-hosts'
      preLoaderRoute: typeof HowItWorksHostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift': {
      id: '/gift'
      path: '/gift'
      fullPath: '/gift'
      preLoaderRoute: typeof GiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-lesson-guide': {
      id: '/first-lesson-guide'
      path: '/first-lesson-guide'
      fullPath: '/first-lesson-guide'
      preLoaderRoute: typeof FirstLessonGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-handling': {
      id: '/data-handling'
      path: '/data-handling'
      fullPath: '/data-handling'
      preLoaderRoute: typeof DataHandlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-an-aide': {
      id: '/become-an-aide'
      path: '/become-an-aide'
      fullPath: '/become-an-aide'
      preLoaderRoute: typeof BecomeAnAideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-mentor': {
      id: '/become-a-mentor'
      path: '/become-a-mentor'
      fullPath: '/become-a-mentor'
      preLoaderRoute: typeof BecomeAMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use-policy': {
      id: '/acceptable-use-policy'
      path: '/acceptable-use-policy'
      fullPath: '/acceptable-use-policy'
      preLoaderRoute: typeof AcceptableUsePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$pathSlug': {
      id: '/p/$pathSlug'
      path: '/p/$pathSlug'
      fullPath: '/p/$pathSlug'
      preLoaderRoute: typeof PPathSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/learner': {
      id: '/onboarding/learner'
      path: '/onboarding/learner'
      fullPath: '/onboarding/learner'
      preLoaderRoute: typeof OnboardingLearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/choice': {
      id: '/onboarding/choice'
      path: '/onboarding/choice'
      fullPath: '/onboarding/choice'
      preLoaderRoute: typeof OnboardingChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/create-path': {
      id: '/mentor/create-path'
      path: '/mentor/create-path'
      fullPath: '/mentor/create-path'
      preLoaderRoute: typeof MentorCreatePathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$mentorSlug': {
      id: '/m/$mentorSlug'
      path: '/m/$mentorSlug'
      fullPath: '/m/$mentorSlug'
      preLoaderRoute: typeof MMentorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/success': {
      id: '/gift/success'
      path: '/success'
      fullPath: '/gift/success'
      preLoaderRoute: typeof GiftSuccessRouteImport
      parentRoute: typeof GiftRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-learning': {
      id: '/_authenticated/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof AuthenticatedMyLearningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/booking-review': {
      id: '/_authenticated/booking-review'
      path: '/booking-review'
      fullPath: '/booking-review'
      preLoaderRoute: typeof AuthenticatedBookingReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/onboarding/learner/results': {
      id: '/onboarding/learner/results'
      path: '/results'
      fullPath: '/onboarding/learner/results'
      preLoaderRoute: typeof OnboardingLearnerResultsRouteImport
      parentRoute: typeof OnboardingLearnerRoute
    }
    '/onboarding/learner/pace': {
      id: '/onboarding/learner/pace'
      path: '/pace'
      fullPath: '/onboarding/learner/pace'
      preLoaderRoute: typeof OnboardingLearnerPaceRouteImport
      parentRoute: typeof OnboardingLearnerRoute
    }
    '/onboarding/learner/device': {
      id: '/onboarding/learner/device'
      path: '/device'
      fullPath: '/onboarding/learner/device'
      preLoaderRoute: typeof OnboardingLearnerDeviceRouteImport
      parentRoute: typeof OnboardingLearnerRoute
    }
    '/c/$categorySlug/$listingSlug': {
      id: '/c/$categorySlug/$listingSlug'
      path: '/c/$categorySlug/$listingSlug'
      fullPath: '/c/$categorySlug/$listingSlug'
      preLoaderRoute: typeof CCategorySlugListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/payouts': {
      id: '/_authenticated/settings/payouts'
      path: '/payouts'
      fullPath: '/settings/payouts'
      preLoaderRoute: typeof AuthenticatedSettingsPayoutsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/operator/preview': {
      id: '/_authenticated/operator/preview'
      path: '/operator/preview'
      fullPath: '/operator/preview'
      preLoaderRoute: typeof AuthenticatedOperatorPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/upcoming-sessions': {
      id: '/_authenticated/dashboard/upcoming-sessions'
      path: '/upcoming-sessions'
      fullPath: '/dashboard/upcoming-sessions'
      preLoaderRoute: typeof AuthenticatedDashboardUpcomingSessionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-orders': {
      id: '/_authenticated/dashboard/my-orders'
      path: '/my-orders'
      fullPath: '/dashboard/my-orders'
      preLoaderRoute: typeof AuthenticatedDashboardMyOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-listing': {
      id: '/_authenticated/dashboard/my-listing'
      path: '/my-listing'
      fullPath: '/dashboard/my-listing'
      preLoaderRoute: typeof AuthenticatedDashboardMyListingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/learner': {
      id: '/_authenticated/dashboard/learner'
      path: '/learner'
      fullPath: '/dashboard/learner'
      preLoaderRoute: typeof AuthenticatedDashboardLearnerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/favorites': {
      id: '/_authenticated/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof AuthenticatedDashboardFavoritesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/earnings-bookings': {
      id: '/_authenticated/dashboard/earnings-bookings'
      path: '/earnings-bookings'
      fullPath: '/dashboard/earnings-bookings'
      preLoaderRoute: typeof AuthenticatedDashboardEarningsBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/earnings': {
      id: '/_authenticated/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof AuthenticatedDashboardEarningsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/aide': {
      id: '/_authenticated/dashboard/aide'
      path: '/aide'
      fullPath: '/dashboard/aide'
      preLoaderRoute: typeof AuthenticatedDashboardAideRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/classroom/$orderId': {
      id: '/_authenticated/classroom/$orderId'
      path: '/classroom/$orderId'
      fullPath: '/classroom/$orderId'
      preLoaderRoute: typeof AuthenticatedClassroomOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificate/$orderId': {
      id: '/_authenticated/certificate/$orderId'
      path: '/certificate/$orderId'
      fullPath: '/certificate/$orderId'
      preLoaderRoute: typeof AuthenticatedCertificateOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/transactions': {
      id: '/_admin/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminAdminTransactionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/search-seo': {
      id: '/_admin/admin/search-seo'
      path: '/search-seo'
      fullPath: '/admin/search-seo'
      preLoaderRoute: typeof AdminAdminSearchSeoRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/reviews': {
      id: '/_admin/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminAdminReviewsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/queue': {
      id: '/_admin/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminAdminQueueRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/listings': {
      id: '/_admin/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminAdminListingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/dashboard/messages/': {
      id: '/_authenticated/dashboard/messages/'
      path: '/'
      fullPath: '/dashboard/messages/'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardMessagesRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/search-seo/': {
      id: '/_admin/admin/search-seo/'
      path: '/'
      fullPath: '/admin/search-seo/'
      preLoaderRoute: typeof AdminAdminSearchSeoIndexRouteImport
      parentRoute: typeof AdminAdminSearchSeoRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-old-messages': {
      id: '/api/public/hooks/cleanup-old-messages'
      path: '/api/public/hooks/cleanup-old-messages'
      fullPath: '/api/public/hooks/cleanup-old-messages'
      preLoaderRoute: typeof ApiPublicHooksCleanupOldMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/messages/$threadId': {
      id: '/_authenticated/dashboard/messages/$threadId'
      path: '/$threadId'
      fullPath: '/dashboard/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedDashboardMessagesRoute
    }
    '/_authenticated/dashboard/learner/upcoming-sessions': {
      id: '/_authenticated/dashboard/learner/upcoming-sessions'
      path: '/upcoming-sessions'
      fullPath: '/dashboard/learner/upcoming-sessions'
      preLoaderRoute: typeof AuthenticatedDashboardLearnerUpcomingSessionsRouteImport
      parentRoute: typeof AuthenticatedDashboardLearnerRoute
    }
    '/_authenticated/dashboard/learner/schedule': {
      id: '/_authenticated/dashboard/learner/schedule'
      path: '/schedule'
      fullPath: '/dashboard/learner/schedule'
      preLoaderRoute: typeof AuthenticatedDashboardLearnerScheduleRouteImport
      parentRoute: typeof AuthenticatedDashboardLearnerRoute
    }
    '/_authenticated/dashboard/learner/purchases': {
      id: '/_authenticated/dashboard/learner/purchases'
      path: '/purchases'
      fullPath: '/dashboard/learner/purchases'
      preLoaderRoute: typeof AuthenticatedDashboardLearnerPurchasesRouteImport
      parentRoute: typeof AuthenticatedDashboardLearnerRoute
    }
    '/_authenticated/dashboard/aide/courses': {
      id: '/_authenticated/dashboard/aide/courses'
      path: '/courses'
      fullPath: '/dashboard/aide/courses'
      preLoaderRoute: typeof AuthenticatedDashboardAideCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardAideRoute
    }
    '/_admin/admin/users/$userId': {
      id: '/_admin/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings/stripe': {
      id: '/_admin/admin/settings/stripe'
      path: '/stripe'
      fullPath: '/admin/settings/stripe'
      preLoaderRoute: typeof AdminAdminSettingsStripeRouteImport
      parentRoute: typeof AdminAdminSettingsRoute
    }
    '/_admin/admin/settings/payments': {
      id: '/_admin/admin/settings/payments'
      path: '/payments'
      fullPath: '/admin/settings/payments'
      preLoaderRoute: typeof AdminAdminSettingsPaymentsRouteImport
      parentRoute: typeof AdminAdminSettingsRoute
    }
    '/_admin/admin/settings/newsletter': {
      id: '/_admin/admin/settings/newsletter'
      path: '/newsletter'
      fullPath: '/admin/settings/newsletter'
      preLoaderRoute: typeof AdminAdminSettingsNewsletterRouteImport
      parentRoute: typeof AdminAdminSettingsRoute
    }
    '/_admin/admin/settings/hero': {
      id: '/_admin/admin/settings/hero'
      path: '/hero'
      fullPath: '/admin/settings/hero'
      preLoaderRoute: typeof AdminAdminSettingsHeroRouteImport
      parentRoute: typeof AdminAdminSettingsRoute
    }
    '/_admin/admin/settings/email-templates': {
      id: '/_admin/admin/settings/email-templates'
      path: '/email-templates'
      fullPath: '/admin/settings/email-templates'
      preLoaderRoute: typeof AdminAdminSettingsEmailTemplatesRouteImport
      parentRoute: typeof AdminAdminSettingsRoute
    }
    '/_admin/admin/settings/categories': {
      id: '/_admin/admin/settings/categories'
      path: '/categories'
      fullPath: '/admin/settings/categories'
      preLoaderRoute: typeof AdminAdminSettingsCategoriesRouteImport
      parentRoute: typeof AdminAdminSettingsRoute
    }
    '/_admin/admin/search-seo/tags': {
      id: '/_admin/admin/search-seo/tags'
      path: '/tags'
      fullPath: '/admin/search-seo/tags'
      preLoaderRoute: typeof AdminAdminSearchSeoTagsRouteImport
      parentRoute: typeof AdminAdminSearchSeoRoute
    }
    '/_admin/admin/settings/pages/': {
      id: '/_admin/admin/settings/pages/'
      path: '/pages'
      fullPath: '/admin/settings/pages/'
      preLoaderRoute: typeof AdminAdminSettingsPagesIndexRouteImport
      parentRoute: typeof AdminAdminSettingsRoute
    }
    '/_authenticated/dashboard/listings/$journeyId/showcase': {
      id: '/_authenticated/dashboard/listings/$journeyId/showcase'
      path: '/listings/$journeyId/showcase'
      fullPath: '/dashboard/listings/$journeyId/showcase'
      preLoaderRoute: typeof AuthenticatedDashboardListingsJourneyIdShowcaseRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/listings/$journeyId/coupons': {
      id: '/_authenticated/dashboard/listings/$journeyId/coupons'
      path: '/listings/$journeyId/coupons'
      fullPath: '/dashboard/listings/$journeyId/coupons'
      preLoaderRoute: typeof AuthenticatedDashboardListingsJourneyIdCouponsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/settings/pages/$pageId': {
      id: '/_admin/admin/settings/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/admin/settings/pages/$pageId'
      preLoaderRoute: typeof AdminAdminSettingsPagesPageIdRouteImport
      parentRoute: typeof AdminAdminSettingsRoute
    }
  }
}

interface AdminAdminSearchSeoRouteChildren {
  AdminAdminSearchSeoTagsRoute: typeof AdminAdminSearchSeoTagsRoute
  AdminAdminSearchSeoIndexRoute: typeof AdminAdminSearchSeoIndexRoute
}

const AdminAdminSearchSeoRouteChildren: AdminAdminSearchSeoRouteChildren = {
  AdminAdminSearchSeoTagsRoute: AdminAdminSearchSeoTagsRoute,
  AdminAdminSearchSeoIndexRoute: AdminAdminSearchSeoIndexRoute,
}

const AdminAdminSearchSeoRouteWithChildren =
  AdminAdminSearchSeoRoute._addFileChildren(AdminAdminSearchSeoRouteChildren)

interface AdminAdminSettingsRouteChildren {
  AdminAdminSettingsCategoriesRoute: typeof AdminAdminSettingsCategoriesRoute
  AdminAdminSettingsEmailTemplatesRoute: typeof AdminAdminSettingsEmailTemplatesRoute
  AdminAdminSettingsHeroRoute: typeof AdminAdminSettingsHeroRoute
  AdminAdminSettingsNewsletterRoute: typeof AdminAdminSettingsNewsletterRoute
  AdminAdminSettingsPaymentsRoute: typeof AdminAdminSettingsPaymentsRoute
  AdminAdminSettingsStripeRoute: typeof AdminAdminSettingsStripeRoute
  AdminAdminSettingsPagesPageIdRoute: typeof AdminAdminSettingsPagesPageIdRoute
  AdminAdminSettingsPagesIndexRoute: typeof AdminAdminSettingsPagesIndexRoute
}

const AdminAdminSettingsRouteChildren: AdminAdminSettingsRouteChildren = {
  AdminAdminSettingsCategoriesRoute: AdminAdminSettingsCategoriesRoute,
  AdminAdminSettingsEmailTemplatesRoute: AdminAdminSettingsEmailTemplatesRoute,
  AdminAdminSettingsHeroRoute: AdminAdminSettingsHeroRoute,
  AdminAdminSettingsNewsletterRoute: AdminAdminSettingsNewsletterRoute,
  AdminAdminSettingsPaymentsRoute: AdminAdminSettingsPaymentsRoute,
  AdminAdminSettingsStripeRoute: AdminAdminSettingsStripeRoute,
  AdminAdminSettingsPagesPageIdRoute: AdminAdminSettingsPagesPageIdRoute,
  AdminAdminSettingsPagesIndexRoute: AdminAdminSettingsPagesIndexRoute,
}

const AdminAdminSettingsRouteWithChildren =
  AdminAdminSettingsRoute._addFileChildren(AdminAdminSettingsRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminListingsRoute: typeof AdminAdminListingsRoute
  AdminAdminQueueRoute: typeof AdminAdminQueueRoute
  AdminAdminReviewsRoute: typeof AdminAdminReviewsRoute
  AdminAdminSearchSeoRoute: typeof AdminAdminSearchSeoRouteWithChildren
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRouteWithChildren
  AdminAdminTransactionsRoute: typeof AdminAdminTransactionsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminListingsRoute: AdminAdminListingsRoute,
  AdminAdminQueueRoute: AdminAdminQueueRoute,
  AdminAdminReviewsRoute: AdminAdminReviewsRoute,
  AdminAdminSearchSeoRoute: AdminAdminSearchSeoRouteWithChildren,
  AdminAdminSettingsRoute: AdminAdminSettingsRouteWithChildren,
  AdminAdminTransactionsRoute: AdminAdminTransactionsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedDashboardAideRouteChildren {
  AuthenticatedDashboardAideCoursesRoute: typeof AuthenticatedDashboardAideCoursesRoute
}

const AuthenticatedDashboardAideRouteChildren: AuthenticatedDashboardAideRouteChildren =
  {
    AuthenticatedDashboardAideCoursesRoute:
      AuthenticatedDashboardAideCoursesRoute,
  }

const AuthenticatedDashboardAideRouteWithChildren =
  AuthenticatedDashboardAideRoute._addFileChildren(
    AuthenticatedDashboardAideRouteChildren,
  )

interface AuthenticatedDashboardLearnerRouteChildren {
  AuthenticatedDashboardLearnerPurchasesRoute: typeof AuthenticatedDashboardLearnerPurchasesRoute
  AuthenticatedDashboardLearnerScheduleRoute: typeof AuthenticatedDashboardLearnerScheduleRoute
  AuthenticatedDashboardLearnerUpcomingSessionsRoute: typeof AuthenticatedDashboardLearnerUpcomingSessionsRoute
}

const AuthenticatedDashboardLearnerRouteChildren: AuthenticatedDashboardLearnerRouteChildren =
  {
    AuthenticatedDashboardLearnerPurchasesRoute:
      AuthenticatedDashboardLearnerPurchasesRoute,
    AuthenticatedDashboardLearnerScheduleRoute:
      AuthenticatedDashboardLearnerScheduleRoute,
    AuthenticatedDashboardLearnerUpcomingSessionsRoute:
      AuthenticatedDashboardLearnerUpcomingSessionsRoute,
  }

const AuthenticatedDashboardLearnerRouteWithChildren =
  AuthenticatedDashboardLearnerRoute._addFileChildren(
    AuthenticatedDashboardLearnerRouteChildren,
  )

interface AuthenticatedDashboardMessagesRouteChildren {
  AuthenticatedDashboardMessagesThreadIdRoute: typeof AuthenticatedDashboardMessagesThreadIdRoute
  AuthenticatedDashboardMessagesIndexRoute: typeof AuthenticatedDashboardMessagesIndexRoute
}

const AuthenticatedDashboardMessagesRouteChildren: AuthenticatedDashboardMessagesRouteChildren =
  {
    AuthenticatedDashboardMessagesThreadIdRoute:
      AuthenticatedDashboardMessagesThreadIdRoute,
    AuthenticatedDashboardMessagesIndexRoute:
      AuthenticatedDashboardMessagesIndexRoute,
  }

const AuthenticatedDashboardMessagesRouteWithChildren =
  AuthenticatedDashboardMessagesRoute._addFileChildren(
    AuthenticatedDashboardMessagesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAideRoute: typeof AuthenticatedDashboardAideRouteWithChildren
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardEarningsRoute: typeof AuthenticatedDashboardEarningsRoute
  AuthenticatedDashboardEarningsBookingsRoute: typeof AuthenticatedDashboardEarningsBookingsRoute
  AuthenticatedDashboardFavoritesRoute: typeof AuthenticatedDashboardFavoritesRoute
  AuthenticatedDashboardLearnerRoute: typeof AuthenticatedDashboardLearnerRouteWithChildren
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRouteWithChildren
  AuthenticatedDashboardMyListingRoute: typeof AuthenticatedDashboardMyListingRoute
  AuthenticatedDashboardMyOrdersRoute: typeof AuthenticatedDashboardMyOrdersRoute
  AuthenticatedDashboardUpcomingSessionsRoute: typeof AuthenticatedDashboardUpcomingSessionsRoute
  AuthenticatedDashboardListingsJourneyIdCouponsRoute: typeof AuthenticatedDashboardListingsJourneyIdCouponsRoute
  AuthenticatedDashboardListingsJourneyIdShowcaseRoute: typeof AuthenticatedDashboardListingsJourneyIdShowcaseRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAideRoute:
      AuthenticatedDashboardAideRouteWithChildren,
    AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
    AuthenticatedDashboardEarningsRoute: AuthenticatedDashboardEarningsRoute,
    AuthenticatedDashboardEarningsBookingsRoute:
      AuthenticatedDashboardEarningsBookingsRoute,
    AuthenticatedDashboardFavoritesRoute: AuthenticatedDashboardFavoritesRoute,
    AuthenticatedDashboardLearnerRoute:
      AuthenticatedDashboardLearnerRouteWithChildren,
    AuthenticatedDashboardMessagesRoute:
      AuthenticatedDashboardMessagesRouteWithChildren,
    AuthenticatedDashboardMyListingRoute: AuthenticatedDashboardMyListingRoute,
    AuthenticatedDashboardMyOrdersRoute: AuthenticatedDashboardMyOrdersRoute,
    AuthenticatedDashboardUpcomingSessionsRoute:
      AuthenticatedDashboardUpcomingSessionsRoute,
    AuthenticatedDashboardListingsJourneyIdCouponsRoute:
      AuthenticatedDashboardListingsJourneyIdCouponsRoute,
    AuthenticatedDashboardListingsJourneyIdShowcaseRoute:
      AuthenticatedDashboardListingsJourneyIdShowcaseRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsPayoutsRoute: typeof AuthenticatedSettingsPayoutsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsPayoutsRoute: AuthenticatedSettingsPayoutsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBookingReviewRoute: typeof AuthenticatedBookingReviewRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedMyLearningRoute: typeof AuthenticatedMyLearningRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedCertificateOrderIdRoute: typeof AuthenticatedCertificateOrderIdRoute
  AuthenticatedClassroomOrderIdRoute: typeof AuthenticatedClassroomOrderIdRoute
  AuthenticatedOperatorPreviewRoute: typeof AuthenticatedOperatorPreviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingReviewRoute: AuthenticatedBookingReviewRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedMyLearningRoute: AuthenticatedMyLearningRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedCertificateOrderIdRoute: AuthenticatedCertificateOrderIdRoute,
  AuthenticatedClassroomOrderIdRoute: AuthenticatedClassroomOrderIdRoute,
  AuthenticatedOperatorPreviewRoute: AuthenticatedOperatorPreviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface GiftRouteChildren {
  GiftSuccessRoute: typeof GiftSuccessRoute
}

const GiftRouteChildren: GiftRouteChildren = {
  GiftSuccessRoute: GiftSuccessRoute,
}

const GiftRouteWithChildren = GiftRoute._addFileChildren(GiftRouteChildren)

interface OnboardingLearnerRouteChildren {
  OnboardingLearnerDeviceRoute: typeof OnboardingLearnerDeviceRoute
  OnboardingLearnerPaceRoute: typeof OnboardingLearnerPaceRoute
  OnboardingLearnerResultsRoute: typeof OnboardingLearnerResultsRoute
}

const OnboardingLearnerRouteChildren: OnboardingLearnerRouteChildren = {
  OnboardingLearnerDeviceRoute: OnboardingLearnerDeviceRoute,
  OnboardingLearnerPaceRoute: OnboardingLearnerPaceRoute,
  OnboardingLearnerResultsRoute: OnboardingLearnerResultsRoute,
}

const OnboardingLearnerRouteWithChildren =
  OnboardingLearnerRoute._addFileChildren(OnboardingLearnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptableUsePolicyRoute: AcceptableUsePolicyRoute,
  BecomeAMentorRoute: BecomeAMentorRoute,
  BecomeAnAideRoute: BecomeAnAideRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DataHandlingRoute: DataHandlingRoute,
  FirstLessonGuideRoute: FirstLessonGuideRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GiftRoute: GiftRouteWithChildren,
  HowItWorksHostsRoute: HowItWorksHostsRoute,
  HowItWorksTrippersRoute: HowItWorksTrippersRoute,
  JourneyWelcomeRoute: JourneyWelcomeRoute,
  LearnerFaqsRoute: LearnerFaqsRoute,
  LoginRoute: LoginRoute,
  MentorAgreementRoute: MentorAgreementRoute,
  MentorFaqsRoute: MentorFaqsRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustAndSafetyRoute: TrustAndSafetyRoute,
  MMentorSlugRoute: MMentorSlugRoute,
  MentorCreatePathRoute: MentorCreatePathRoute,
  MessagesThreadIdRoute: MessagesThreadIdRoute,
  OnboardingChoiceRoute: OnboardingChoiceRoute,
  OnboardingLearnerRoute: OnboardingLearnerRouteWithChildren,
  PPathSlugRoute: PPathSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  CCategorySlugListingSlugRoute: CCategorySlugListingSlugRoute,
  ApiPublicHooksCleanupOldMessagesRoute: ApiPublicHooksCleanupOldMessagesRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
